apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-config
data:
  app.conf: |
    appname = casdoor
    httpport = 80
    runmode = dev
    SessionOn = true
    copyrequestbody = true
    driverName = mysql
    dataSourceName = root:123456@tcp(localhost:3306)/
    dbName = casdoor
    redisEndpoint =
    defaultStorageProvider = 
    isCloudIntranet = false
    socks5Proxy = "127.0.0.1:10808"
    verificationCodeTimeout = 10
    initScore = 2000
    logPostOnly = true
    origin = "https://door.casbin.com"